name: build

on:
  pull_request:
  push:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ${{ case(matrix.platform == 'x86_64', 'ubuntu-24.04', 'ubuntu-24.04-arm64') }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - x86_64
          - aarch64

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: build
        run: |
          make ${{ matrix.platform }}

      - uses: docker/setup-qemu-action@1f40c72289eff860ee54a304f1438e3cff362e0a # v4.3.0
      - uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0
      - name: test
        run: |
          make test-${{ matrix.platform }}

      - name: Configure AWS Credentials
        uses: fuller-inc/actions-aws-assume-role@db10fc9ddce76ac14ce9182c2433f497580bec93 # v1.9.2
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::445285296882:role/rpm-repository-users-MitamaeRole-1OPFWBU8880WC
          role-session-tagging: true
      - name: upload
        run: |
          make upload
