name: build

on:
  pull_request:
  push:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - x86_64
          - aarch64

    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          make ${{ matrix.platform }}

      - name: Configure AWS Credentials
        uses: shogo82148/actions-aws-assume-role@v1
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::445285296882:role/rpm-repository-users-MitamaeRole-1OPFWBU8880WC
          role-session-tagging: true
      - name: upload
        if: github.event_name == 'release'
        run: |
          make upload
