name: build

on:
  pull_request:
  push:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - x86_64
          - aarch64

    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          make ${{ matrix.platform }}
