name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write

jobs:
  prepare:
    runs-on: ubuntu-slim
    steps:
      - name: Create GitHub Draft Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create "${GITHUB_REF_NAME}" --repo "${GITHUB_REPOSITORY}" --verify-tag --draft --generate-notes

  build:
    needs: prepare
    runs-on: ${{ case(matrix.platform == 'x86_64', 'ubuntu-26.04', 'ubuntu-26.04-arm') }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - x86_64
          - aarch64

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: build
        run: |
          make ${{ matrix.platform }}

      - uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v4.4.0
      - uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1
      - name: test
        run: |
          make test-${{ matrix.platform }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e1253824e5c10ff9df46874f81ed3ec929e19cfd # v6.3.0
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::445285296882:role/rpm-repository-users-MitamaeRole-1OPFWBU8880WC
      - name: upload to S3
        run: |
          make upload
      - name: upload to GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload "${GITHUB_REF_NAME}" "${{ matrix.platform }}.build/RPMS/${{ matrix.platform }}/*.${{ matrix.platform }}.rpm" --repo "${GITHUB_REPOSITORY}" --clobber

  release:
    needs: build
    runs-on: ubuntu-slim
    steps:
      - name: Release Assets
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release edit "${GITHUB_REF_NAME}" --repo "${GITHUB_REPOSITORY}" --verify-tag --draft=false
